############################
## CHANGE THESE
############################

baseURL: 'https://qldo.github.io/blog'
title: 'sorrow'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


